README.md
=> include publication in readme

climsight.py, download_data.sh
=> adding UN population data

climsight.py
Making sure "Not known" actually gets displayed when there is no information available.
=> quick bug fix of biodiversity API

climsight.py
=> allow hitting enter instead of pressing "generate" button

climsight.py, download_data.sh
I added additional data sets from natural earth data that check if the location that has been clicked is either in the ocean or in a lake or near a river. If so, the user will get a warning that they should rather select a land area. However, the programme does not abort, only the results may not be as good as normally.
Additionally, I extracted more information that are anyway stored in the OpenStreetMap Layer, in particular "extratags" and "namedetails" that provide us more local information. 
closes #26 and part of #16
=> water body data and osm additional details

climsight.py
=> added a switch to de/activate additional information being displayed

climsight.py
With the merge of 0a66049fb298b74cc009dd62e3a2492de972a92f a old version of the plotting had been re-added to the code which was previously removed. I removed it again. The same code appears a little bit further done in the "additional data" section, it was just there twice.
=> remove accidentally added additional plotting

Dockerfile, README.md, src/climsight/launch.py
Modified the Dockerfile to fit the new structure and updated the README.md accordingly.
=> Docker correction

.github/workflows/python-package.yml
action will run on PR to main:
- install python 3.10
- install climsight from "./"
- run flake8 to check for code errors
=> Create action for package installation and test

pyproject.toml
changed version of project to 0.2.0 , this version uploaded to pypi. added readme to pyproject
=> project uploaded to pypi 

README.md, src/climsight/climsight.py
allow option to run climsight from different config file paths
=> Choose config file

config.yml, config_tco1279.yml, config_tco319.yml
=> make newest openai version the default one

config.yml, config_tco1279.yml, config_tco319.yml, src/climsight/climsight_engine.py, src/climsight/geo_functions.py, src/climsight/streamlit_interface.py, src/climsight/terminal_interface.py
fix bug in address request if point on ocean
=> Fix onland

config.yml, config_tco1279.yml, config_tco319.yml, data_sources.yml, environment.yml, pyproject.toml, src/climsight/climsight_classes.py, src/climsight/climsight_engine.py, src/climsight/extract_climatedata_functions.py, src/climsight/smart_agent.py, src/climsight/streamlit_interface.py, src/climsight/terminal_interface.py
This update brings support for high-resolution data (Healpix, 512 resolution tested with NextGem, 4 variables). Key changes include:
- New file handler: Added functions to process and read Healpix data as climate input.
- Interface adjustments: Updated and fixed bugs in the interfaces to support high-resolution workflows smoothly.
- Agent reconfiguration:
- Smart agent now runs after the data agent.
- All agents are set to run in parallel for better efficiency.
- Smart agent processes high-resolution data directly from the data agent instead of raw files.
=> High resolution data (Nextgem)

src/climsight/climsight_engine.py, src/climsight/extract_climatedata_functions.py, src/climsight/rag.py
I extended the logging. The climsight.log file now contains all steps that happen in between, meaning all "raw outputs" that are returned from the agents, for better tracebility.
=> extended logging

src/climsight/climsight_engine.py, src/climsight/streamlit_interface.py
=> fix lon_default to not become endlessly big/small

src/climsight/streamlit_interface.py
remove the llmModeKey_box from the form, as we tend to run the agent mode, direct mode is for development only
=> remove the llmModeKey_box 

Dockerfile, README.md, pyproject.toml
updated readme and installation with pip
=> Release v1

src/climsight/climsight_engine.py, src/climsight/smart_agent.py, src/climsight/stream_handler.py, src/climsight/streamlit_interface.py, src/climsight/terminal_interface.py
Added progress updates to the agent workflow by integrating descriptive status messages at key sequential stages in the langgraph execution pipeline.
=> adding report current stage during rquests

src/climsight/climsight_engine.py, src/climsight/streamlit_interface.py
=> add box with model selection to streamlit interface

src/climsight/evaluation.py
to run evaluation:
`python src/climsight/evaluation.py`
QA.txt has 30 question for evaluation 
to test remove 29 of them
=> adjust evaluatino to paper version

config.yml, src/climsight/climsight_classes.py, src/climsight/climsight_engine.py, src/climsight/question_runner.py, src/climsight/rag.py, src/climsight/smart_agent.py, src/climsight/streamlit_interface.py, src/climsight/terminal_interface.py
You can now run this with local LLMs via server API.
Tested with vLLM using LLaMA 3 (70B and 8B).
Set:openai_api_base="http://localhost:8000/v1"
Change it if your server runs on a different address.
Note: Doesn’t work with Ollama (no tool support).
To use on a cluster, open an SSH tunnel to localhost:8000.
=> Support for Open LLMs

sequential/question_map.py
Add support for displaying evaluation/QA.yml questions and answers on the map. Markers now indicate answer availability, and clicking a marker with an answer shows it below the map.
=> added QA to the map from evaluation

.github/workflows/pytest.yml, .github/workflows/python-package.yml
=> patch for 3.11
